# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        cache: 'maven'
    - name: Check java version 
      run: java -version
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  docker:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - name: Download artifact from maven job
        uses: actions/download-artifact@v3
        with:
          name: java-app
      - name: Logging in to Docker
        run: docker login ghcr.io -u USERNAME -p ${{ github.token }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/ahalbrucker/cubix/1/homework/app:springboot
      - name: Pushing the Docker image
        run: docker push ghcr.io/ahalbrucker/cubix/1/homework/app:springboot

  verify:
    runs-on: ubuntu-latest
    needs: docker
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Verify the Docker image
        run: ./verify-image.sh
